### PR TITLE
Fix openDocumentSettingsPanel and tests

### LINKED ISSUE #36: `openDocumentSettingsPanel` & `openDocumentSettingsSidebar` tests are failing in WP minimum env.
### Describe the bug

We have added WP minimum env(5.2) in GH action to test commands with 5.2 and `openDocumentSettingsPanel` & `openDocumentSettingsSidebar` tests are [failing](https://github.com/10up/cypress-wp-utils/runs/5748152338?check_suite_focus=true) on it.
```
1) Commands: openDocumentSettings*
       Should be able to open (don't close) Status Panel on a new post:
     AssertionError: Timed out retrying after 4000ms: Expected to find element: `button[aria-label="Close dialog"]`, but never found it.
      at Context.eval (http://localhost:8889/__cypress/tests?p=tests/cypress/integration/open-document-settings.test.js:116:8)
```

### Steps to Reproduce

Test against WordPress core 5.2

### Screenshots, screen recording, code snippet

image

### Environment information

_No response_

### WordPress information

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by cadic**
### Description of the Change

This PR fixes multiple issues with `openDocumentSettingsPanel` and `openDocumentSettingsSidebar` commands:
- Close welcome guide action failed in older WordPress versions, fixed in #42 
- In WordPress prior to 5.4 the Document settings tab is called "Document", in later core versions it is renamed to the current post type name (Post, Page, etc.)
- In WordPress prior to 5.4 panel names were called with capitalized style. Starting from 5.4 panel names are called with Upper-case-first style.

Closes #36

Tested against every WordPress core major release from the minimum 5.2 to the latest nightly build.

### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### CODE REVIEW

File: src/commands/open-document-settings-panel.ts [hunk 1]
```diff
@@ -20,18 +23,24 @@ export const openDocumentSettingsPanel = (name: string, tab = 'Post'): void => {
...
-      const $panel = $button.parents('.components-panel__body');
+  // WordPress prior to 5.4 is using upper-case-words for panel names
+  // WordPress 5.3 and below: "Status & Visibility"
+  // WordPress 5.4 and after: "Status & visibility"
+  const ucFirstName = ucFirst(name);
+  const ucWordsName = capitalize(name);
+
+  const panelButtonSelector = `.components-panel__body .components-panel__body-title button:contains("${ucWordsName}"),.components-panel__body .components-panel__body-title button:contains("${ucFirstName}")`;
+
+  cy.get(panelButtonSelector).then($button => {
```
Comment (cadic) [inline src/commands/open-document-settings-panel.ts:34]: Some tabs (Tags, Categories, etc.) does not exist after the DOM is ready. They are added a few moments later after REST calls. In this case, using `cy.get('button').contains(name)` doesn't work: `cy.get()` is called before the tabs appear in DOM, finds other panels, but fails to filter any containing the name.

Using new panelButtonSelector with `button:contains("tab name")` to wait for the elements to appear in DOM.

**Review by iamdharmesh — APPROVED** [review]
@cadic Thanks for fixing this.
LGTM!! :+1:
